// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uGxoRb5owhYSHdB4mcd3xyvpzUOHOK8',
    appId: '1:661355864569:web:d75795cf38b2362314dd28',
    messagingSenderId: '661355864569',
    projectId: 'fitness-tracker-4f213',
    authDomain: 'fitness-tracker-4f213.firebaseapp.com',
    storageBucket: 'fitness-tracker-4f213.firebasestorage.app',
    measurementId: 'G-M582FGFJRJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9votSmoQSQA8QnAHd65zTH1h2Ni2AL0',
    appId: '1:661355864569:ios:7e3268d4ce87e43814dd28',
    messagingSenderId: '661355864569',
    projectId: 'fitness-tracker-4f213',
    storageBucket: 'fitness-tracker-4f213.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk9votSmoQSQA8QnAHd65zTH1h2Ni2AL0',
    appId: '1:661355864569:ios:7e3268d4ce87e43814dd28',
    messagingSenderId: '661355864569',
    projectId: 'fitness-tracker-4f213',
    storageBucket: 'fitness-tracker-4f213.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uGxoRb5owhYSHdB4mcd3xyvpzUOHOK8',
    appId: '1:661355864569:web:ab674e9574c4755414dd28',
    messagingSenderId: '661355864569',
    projectId: 'fitness-tracker-4f213',
    authDomain: 'fitness-tracker-4f213.firebaseapp.com',
    storageBucket: 'fitness-tracker-4f213.firebasestorage.app',
    measurementId: 'G-C0RHGZRCT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-zGL3offpFuyT2LRxWAFy8eoneV4dHA',
    appId: '1:661355864569:android:15fbadfaf7ffd6d114dd28',
    messagingSenderId: '661355864569',
    projectId: 'fitness-tracker-4f213',
    storageBucket: 'fitness-tracker-4f213.firebasestorage.app',
  );

}